### PR TITLE
Fix deprecated warning.(Config to RbConfig)

### PR DESCRIPTION
**Pull request by ukstudio**
I fix deprecated warning.
Should using RbConfig.
Please, merge my commit.

### CODE REVIEW

**Comment by ReneB** [comment]
Found to work with Ruby >= 1.8.5. +1

**Comment by mikedfunk** [comment]
:+1:

**Comment by kevinburke** [comment]
Hi, 
This library has not been maintained for over a year, this has been fixed in https://github.com/kevinburke/observr, you may want to try downloading that gem.

**Comment by mikedfunk** [comment]
Thanks @kevinburke

**Pull request closed without merging**
